### ISSUE TITLE
rootfs.tgz can't access any more

### ISSUE THREAD

**Issue by rmrf** [friendlyarm/sd-fuse_nanopi#5]
the wget inside mkimage.sh and mkrootfs.sh which need get tgz file from 112.124.9.243, but this url can't access any more. 
would you please put this file on more reliable place?
Thanks!
the url:
http://112.124.9.243/dvdfiles/NanoPi/nanopi-debian-jessie-rootfs.tgz

**Comment by lawrencetg** [comment]
i have updated the url, thanks your feedback!

**Comment by rmrf** [comment]
Thank you!
